name: Recovery Build

on:
  workflow_dispatch:
    inputs:
      MANIFEST_URL:
        description: 'MANIFEST_URL'
        required: false
      MANIFEST_BRANCH:
        description: 'MANIFEST_BRANCH'
        required: false
      DEVICE_TREE_URL:
        description: 'DEVICE_TREE_URL'
        required: false
      DEVICE_TREE_BRANCH:
        description: 'DEVICE_TREE_BRANCH'
        required: false
      DEVICE_PATH:
        description: 'DEVICE_PATH'
        required: false
      COMMON_TREE_URL:
        description: 'COMMON_TREE_URL'
        required: false
      COMMON_PATH:
        description: 'COMMON_PATH'
        required: false
      DEVICE_NAME:
        description: 'DEVICE_NAME'
        required: false
      MAKEFILE_NAME:
        description: 'MAKEFILE_NAME'
        required: false
      BUILD_TARGET:
        description: 'BUILD_TARGET'
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Check Out
      uses: actions/checkout@v4

    - name: Cleanup
      uses: rokibhasansagar/slimhub_actions@main

    - name: Prepare the environment
      run: |
        sudo apt update && sudo apt upgrade -y
        DEBIAN_FRONTEND=noninteractive sudo apt install -yq \
            linux-modules-extra-$(uname -r) \
            gperf gcc-multilib gcc-10-multilib g++-multilib g++-10-multilib \
            libc6-dev lib32ncurses-dev x11proto-core-dev libx11-dev tree lib32z-dev libgl1-mesa-dev libxml2-utils \
            xsltproc bc ccache lib32readline-dev lib32z1-dev liblz4-tool libncurses-dev libsdl1.2-dev \
            build-essential libgtk-3-dev libglu1-mesa-dev freeglut3-dev git libxml2 lzop pngcrush schedtool squashfs-tools \
            imagemagick libbz2-dev lzma ncftp qemu-user-static libstdc++-10-dev libncurses6 python3 tar

    - name: Install OpenJDK
      uses: actions/setup-java@v5
      with:
        distribution: 'zulu'
        java-version: '11'

    - name: Install repo
      run: |
        sudo apt-get update
        sudo apt-get install -y repo

    - name: Initialize repo
      run: |
        mkdir workspace
        cd workspace
        echo "workspace-folder=$(pwd)" >> $GITHUB_OUTPUT
        git config --global user.name "Nico170420"
        git config --global user.email "b170420nc@gmail.com"
        
        REAL_M_URL="${{ github.event.inputs.MANIFEST_URL }}"
        if [ -z "$REAL_M_URL" ]; then
          REAL_M_URL="https://github.com/minimal-manifest-twrp/platform_manifest_twrp_omni"
        fi
        
        REAL_M_BRANCH="${{ github.event.inputs.MANIFEST_BRANCH }}"
        if [ -z "$REAL_M_BRANCH" ]; then
          REAL_M_BRANCH="twrp-8.1"
        fi
        
        repo init --depth=1 -u $REAL_M_URL -b $REAL_M_BRANCH
      id: pwd

    - name: Repo Sync
      run: |
        repo sync -c -j4 --force-sync --no-clone-bundle --no-tags
      working-directory: workspace

    - name: Clone device tree
      run: |
        REAL_D_URL="${{ github.event.inputs.DEVICE_TREE_URL }}"
        if [ -z "$REAL_D_URL" ]; then
          REAL_D_URL="https://github.com/aosp-galaxy/android_device_samsung_gtaxlwi"
        fi
        
        REAL_D_BRANCH="${{ github.event.inputs.DEVICE_TREE_BRANCH }}"
        if [ -z "$REAL_D_BRANCH" ]; then
          REAL_D_BRANCH="omni-8.1"
        fi
        
        REAL_D_PATH="device/samsung/gtaxlwi"
        
        git clone $REAL_D_URL -b $REAL_D_BRANCH ./$REAL_D_PATH || git clone https://github.com/minimal-manifest-twrp/platform_manifest_twrp_omni ./$REAL_D_PATH
      working-directory: ${{ steps.pwd.outputs.workspace-folder }}

    - name: Check Build Tree
      uses: haya14busa/action-cond@v1
      id: buildtree
      with:
        cond: 'false'
        if_true: twrp
        if_false: omni

    - name: Sync Device Dependencies
      run: |
        if [ -f ${GITHUB_WORKSPACE}/scripts/convert.sh ]; then
          bash ${GITHUB_WORKSPACE}/scripts/convert.sh device/samsung/gtaxlwi/omni.dependencies || true
        fi
        repo sync -c -j4 --force-sync --no-clone-bundle --no-tags || true
      working-directory: ${{ steps.pwd.outputs.workspace-folder }}
      continue-on-error: true

    - name: Set Swap Space
      uses: pierotofy/set-swap-space@master
      with:
        swap-size-gb: 12

    - name: Building recovery
      run: |
        source build/envsetup.sh
        export ALLOW_MISSING_DEPENDENCIES=true
        lunch omni_gtaxlwi-eng && make clean && make recoveryimage -j$(nproc --all)
      working-directory: ${{ steps.pwd.outputs.workspace-folder }}

    - name: Upload to Release
      uses: softprops/action-gh-release@v2
      with:
        files: | 
          workspace/out/target/product/gtaxlwi/recovery.img
        name: sm-t583-twrp-build
        tag_name: ${{ github.run_id }}
        body: |
          삼성 갤럭시 탭 Advanced2 (SM-T583) 커스텀 TWRP 빌드 성공!
          베이스 기종 소스: SM-T580 (gtaxlwi) Android 8.1 Oreo 기반 컴파일 완료.
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
